/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ShortcutsRouteImport } from './routes/shortcuts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationsIntegrationIdRouteImport } from './routes/integrations.$integrationId'
import { Route as BoardAddVoiceTaskRouteImport } from './routes/board.add-voice-task'
import { Route as BoardAddTaskRouteImport } from './routes/board.add-task'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortcutsRoute = ShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIntegrationIdRoute =
  IntegrationsIntegrationIdRouteImport.update({
    id: '/integrations/$integrationId',
    path: '/integrations/$integrationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BoardAddVoiceTaskRoute = BoardAddVoiceTaskRouteImport.update({
  id: '/add-voice-task',
  path: '/add-voice-task',
  getParentRoute: () => BoardRoute,
} as any)
const BoardAddTaskRoute = BoardAddTaskRouteImport.update({
  id: '/add-task',
  path: '/add-task',
  getParentRoute: () => BoardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/groups': typeof GroupsRoute
  '/notes': typeof NotesRoute
  '/planning': typeof PlanningRoute
  '/processes': typeof ProcessesRoute
  '/projects': typeof ProjectsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/shortcuts': typeof ShortcutsRoute
  '/skills': typeof SkillsRoute
  '/tags': typeof TagsRoute
  '/board/add-task': typeof BoardAddTaskRoute
  '/board/add-voice-task': typeof BoardAddVoiceTaskRoute
  '/integrations/$integrationId': typeof IntegrationsIntegrationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/groups': typeof GroupsRoute
  '/notes': typeof NotesRoute
  '/planning': typeof PlanningRoute
  '/processes': typeof ProcessesRoute
  '/projects': typeof ProjectsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/shortcuts': typeof ShortcutsRoute
  '/skills': typeof SkillsRoute
  '/tags': typeof TagsRoute
  '/board/add-task': typeof BoardAddTaskRoute
  '/board/add-voice-task': typeof BoardAddVoiceTaskRoute
  '/integrations/$integrationId': typeof IntegrationsIntegrationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/groups': typeof GroupsRoute
  '/notes': typeof NotesRoute
  '/planning': typeof PlanningRoute
  '/processes': typeof ProcessesRoute
  '/projects': typeof ProjectsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/shortcuts': typeof ShortcutsRoute
  '/skills': typeof SkillsRoute
  '/tags': typeof TagsRoute
  '/board/add-task': typeof BoardAddTaskRoute
  '/board/add-voice-task': typeof BoardAddVoiceTaskRoute
  '/integrations/$integrationId': typeof IntegrationsIntegrationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/groups'
    | '/notes'
    | '/planning'
    | '/processes'
    | '/projects'
    | '/schedule'
    | '/settings'
    | '/shortcuts'
    | '/skills'
    | '/tags'
    | '/board/add-task'
    | '/board/add-voice-task'
    | '/integrations/$integrationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/groups'
    | '/notes'
    | '/planning'
    | '/processes'
    | '/projects'
    | '/schedule'
    | '/settings'
    | '/shortcuts'
    | '/skills'
    | '/tags'
    | '/board/add-task'
    | '/board/add-voice-task'
    | '/integrations/$integrationId'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/groups'
    | '/notes'
    | '/planning'
    | '/processes'
    | '/projects'
    | '/schedule'
    | '/settings'
    | '/shortcuts'
    | '/skills'
    | '/tags'
    | '/board/add-task'
    | '/board/add-voice-task'
    | '/integrations/$integrationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRouteWithChildren
  GroupsRoute: typeof GroupsRoute
  NotesRoute: typeof NotesRoute
  PlanningRoute: typeof PlanningRoute
  ProcessesRoute: typeof ProcessesRoute
  ProjectsRoute: typeof ProjectsRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  ShortcutsRoute: typeof ShortcutsRoute
  SkillsRoute: typeof SkillsRoute
  TagsRoute: typeof TagsRoute
  IntegrationsIntegrationIdRoute: typeof IntegrationsIntegrationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortcuts': {
      id: '/shortcuts'
      path: '/shortcuts'
      fullPath: '/shortcuts'
      preLoaderRoute: typeof ShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$integrationId': {
      id: '/integrations/$integrationId'
      path: '/integrations/$integrationId'
      fullPath: '/integrations/$integrationId'
      preLoaderRoute: typeof IntegrationsIntegrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/add-voice-task': {
      id: '/board/add-voice-task'
      path: '/add-voice-task'
      fullPath: '/board/add-voice-task'
      preLoaderRoute: typeof BoardAddVoiceTaskRouteImport
      parentRoute: typeof BoardRoute
    }
    '/board/add-task': {
      id: '/board/add-task'
      path: '/add-task'
      fullPath: '/board/add-task'
      preLoaderRoute: typeof BoardAddTaskRouteImport
      parentRoute: typeof BoardRoute
    }
  }
}

interface BoardRouteChildren {
  BoardAddTaskRoute: typeof BoardAddTaskRoute
  BoardAddVoiceTaskRoute: typeof BoardAddVoiceTaskRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardAddTaskRoute: BoardAddTaskRoute,
  BoardAddVoiceTaskRoute: BoardAddVoiceTaskRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRouteWithChildren,
  GroupsRoute: GroupsRoute,
  NotesRoute: NotesRoute,
  PlanningRoute: PlanningRoute,
  ProcessesRoute: ProcessesRoute,
  ProjectsRoute: ProjectsRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  ShortcutsRoute: ShortcutsRoute,
  SkillsRoute: SkillsRoute,
  TagsRoute: TagsRoute,
  IntegrationsIntegrationIdRoute: IntegrationsIntegrationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
