/**
 * Group-related types for Nightshift
 * Groups are purely organizational and independent of filesystem structure
 */

/**
 * Group entry stored in ~/.nightshift/sync/groups.json
 */
export interface Group {
  /** Unique group identifier (e.g., grp_001) */
  id: string

  /** Display name for the group */
  name: string

  /** Optional description */
  description: string | null

  /** IDs of projects in this group */
  projectIds: string[]

  /** Parent group ID for nesting (null = root level group) */
  parentId: string | null

  /** Display color (hex format) */
  color: string | null

  /** Custom icon - either a Lucide icon name or a file path/URL to an image */
  icon: string | null

  /** When the group was created */
  createdAt: string
}

/**
 * Group node with children for tree representation
 */
export interface GroupTreeNode extends Group {
  /** Direct child groups */
  children: GroupTreeNode[]
  /** Depth level in the tree (0 = root) */
  depth: number
}

/**
 * Groups registry file structure
 */
export interface GroupsRegistry {
  groups: Group[]
}

/**
 * Create a new group with default values
 */
export function createGroup(
  id: string,
  name: string,
  options: Partial<Group> = {}
): Group {
  return {
    id,
    name,
    description: null,
    projectIds: [],
    parentId: null,
    color: null,
    icon: null,
    createdAt: new Date().toISOString(),
    ...options
  }
}

/**
 * Maximum allowed nesting depth for groups
 */
export const MAX_GROUP_NESTING_DEPTH = 5

/**
 * Generate a unique group ID
 */
export function generateGroupId(): string {
  return `grp_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 7)}`
}

/**
 * Default group colors for UI
 */
export const GROUP_COLORS = [
  '#4A90D9', // Blue
  '#7B68EE', // Purple
  '#3CB371', // Green
  '#FF6B6B', // Red
  '#FFB347', // Orange
  '#20B2AA', // Teal
  '#DDA0DD', // Plum
  '#87CEEB' // Sky Blue
] as const

/**
 * Available Lucide icon names for groups
 * Comprehensive selection matching PROJECT_ICONS for consistency
 */
export const GROUP_ICONS = [
  // Organization & Structure
  'Layers',
  'Layers2',
  'Layers3',
  'FolderKanban',
  'Folders',
  'Folder',
  'FolderOpen',
  'FolderClosed',
  'FolderTree',
  'FolderGit2',
  'FolderCode',
  'FolderDot',
  'FolderInput',
  'FolderOutput',
  'FolderSearch',
  'FolderSymlink',
  'Boxes',
  'Box',
  'BoxSelect',
  'Package',
  'PackageOpen',
  'PackageCheck',
  'PackagePlus',
  'PackageSearch',
  'PackageMinus',
  'PackageX',
  'Packages',
  'Grid2x2',
  'Grid3x3',
  'LayoutGrid',
  'LayoutList',
  'LayoutDashboard',
  'LayoutTemplate',
  'LayoutPanelLeft',
  'LayoutPanelTop',
  'Layout',
  'Blocks',
  'Component',
  'Puzzle',
  'Shapes',
  'CircleDot',
  'SquareStack',
  'Library',
  'LibraryBig',
  'Archive',
  'ArchiveRestore',
  'ArchiveX',
  'Inbox',
  'Combine',
  'Group',
  'Ungroup',
  'Merge',
  'Split',
  'Kanban',
  'KanbanSquare',
  'KanbanSquareDashed',
  'ListTree',
  'Workflow',
  'SplitSquareHorizontal',
  'SplitSquareVertical',
  'Columns2',
  'Columns3',
  'Columns4',
  'Rows2',
  'Rows3',
  'Rows4',

  // Favorites & Tags
  'Star',
  'StarHalf',
  'StarOff',
  'Stars',
  'Heart',
  'HeartCrack',
  'HeartHandshake',
  'HeartOff',
  'HeartPulse',
  'Bookmark',
  'BookmarkCheck',
  'BookmarkMinus',
  'BookmarkPlus',
  'BookmarkX',
  'Bookmarks',
  'Flag',
  'FlagOff',
  'FlagTriangleLeft',
  'FlagTriangleRight',
  'Tag',
  'Tags',
  'Pin',
  'PinOff',
  'Sparkles',
  'Sparkle',
  'Gem',
  'Crown',
  'Award',
  'Medal',
  'Trophy',
  'BadgeCheck',
  'BadgeInfo',
  'BadgeMinus',
  'BadgePlus',
  'BadgeX',
  'BadgeAlert',
  'Verified',
  'ThumbsUp',
  'ThumbsDown',
  'Sticker',

  // Status & Priority
  'Zap',
  'ZapOff',
  'Rocket',
  'Flame',
  'FlameKindling',
  'AlertCircle',
  'AlertTriangle',
  'AlertOctagon',
  'Info',
  'CircleAlert',
  'TriangleAlert',
  'OctagonAlert',
  'OctagonX',
  'Ban',
  'CircleOff',
  'XOctagon',
  'Clock',
  'Clock1',
  'Clock2',
  'Clock3',
  'Clock4',
  'Clock5',
  'Clock6',
  'Clock7',
  'Clock8',
  'Clock9',
  'Clock10',
  'Clock11',
  'Clock12',
  'Timer',
  'TimerOff',
  'TimerReset',
  'Hourglass',
  'AlarmClock',
  'AlarmClockCheck',
  'AlarmClockMinus',
  'AlarmClockOff',
  'AlarmClockPlus',
  'CalendarDays',
  'Calendar',
  'CalendarCheck',
  'CalendarCheck2',
  'CalendarClock',
  'CalendarCog',
  'CalendarFold',
  'CalendarHeart',
  'CalendarMinus',
  'CalendarMinus2',
  'CalendarOff',
  'CalendarPlus',
  'CalendarPlus2',
  'CalendarRange',
  'CalendarSearch',
  'CalendarX',
  'CalendarX2',
  'CalendarArrowDown',
  'CalendarArrowUp',
  'CheckCircle',
  'CheckCircle2',
  'CheckSquare',
  'CheckSquare2',
  'Check',
  'CheckCheck',
  'CircleCheck',
  'CircleCheckBig',
  'SquareCheck',
  'SquareCheckBig',
  'ListChecks',
  'ListTodo',
  'List',
  'ListEnd',
  'ListFilter',
  'ListMinus',
  'ListOrdered',
  'ListPlus',
  'ListX',
  'ListMusic',
  'ListRestart',
  'ListStart',
  'ListVideo',
  'History',
  'Redo',
  'Redo2',
  'Undo',
  'Undo2',
  'RotateCcw',
  'RotateCw',
  'RefreshCcw',
  'RefreshCcwDot',
  'RefreshCw',
  'RefreshCwOff',

  // Categories & Types
  'Home',
  'House',
  'HousePlug',
  'HousePlus',
  'Building',
  'Building2',
  'Landmark',
  'Factory',
  'Store',
  'Warehouse',
  'Briefcase',
  'BriefcaseBusiness',
  'BriefcaseConveyorBelt',
  'BriefcaseMedical',
  'GraduationCap',
  'BookOpen',
  'BookOpenCheck',
  'BookOpenText',
  'Book',
  'BookMarked',
  'BookText',
  'BookType',
  'BookUser',
  'BookCopy',
  'BookDashed',
  'BookDown',
  'BookHeadphones',
  'BookHeart',
  'BookImage',
  'BookKey',
  'BookLock',
  'BookMinus',
  'BookPlus',
  'BookUp',
  'BookUp2',
  'BookX',
  'Books',
  'Notebook',
  'NotebookPen',
  'NotebookTabs',
  'NotebookText',
  'FileStack',
  'ScrollText',
  'Scroll',

  // Tech & Development
  'Code',
  'Code2',
  'CodeXml',
  'Braces',
  'Brackets',
  'Terminal',
  'TerminalSquare',
  'SquareTerminal',
  'SquareCode',
  'SquareFunction',
  'FileCode',
  'FileCode2',
  'FileJson',
  'FileJson2',
  'FileText',
  'FileCog',
  'FileType',
  'FileType2',
  'FileBadge',
  'FileBadge2',
  'FileCheck',
  'FileCheck2',
  'FileDiff',
  'FileDigit',
  'FileInput',
  'FileOutput',
  'FilePlus',
  'FilePlus2',
  'FileSearch',
  'FileSearch2',
  'FileSliders',
  'FileTerminal',
  'FileUp',
  'FileDown',
  'FileX',
  'FileX2',
  'FilePen',
  'FilePenLine',
  'Files',
  'Database',
  'DatabaseBackup',
  'DatabaseZap',
  'Server',
  'ServerCog',
  'ServerCrash',
  'ServerOff',
  'Cloud',
  'CloudCog',
  'CloudDownload',
  'CloudUpload',
  'CloudOff',
  'Globe',
  'Globe2',
  'GlobeLock',
  'Earth',
  'Chrome',
  'Laptop',
  'LaptopMinimal',
  'Monitor',
  'MonitorCheck',
  'MonitorCog',
  'MonitorDot',
  'MonitorDown',
  'MonitorOff',
  'MonitorPause',
  'MonitorPlay',
  'MonitorSmartphone',
  'MonitorSpeaker',
  'MonitorStop',
  'MonitorUp',
  'MonitorX',
  'Smartphone',
  'SmartphoneCharging',
  'SmartphoneNfc',
  'Tablet',
  'TabletSmartphone',
  'Cpu',
  'Microchip',
  'CircuitBoard',
  'MemoryStick',
  'HardDrive',
  'HardDriveDownload',
  'HardDriveUpload',
  'HardHat',
  'Usb',
  'BrainCircuit',
  'BrainCog',
  'Brain',
  'Bot',
  'BotMessageSquare',
  'BotOff',
  'Binary',
  'Bug',
  'BugOff',
  'BugPlay',
  'Regex',
  'Variable',
  'GitBranch',
  'GitBranchPlus',
  'GitCommit',
  'GitCommitHorizontal',
  'GitCommitVertical',
  'GitCompare',
  'GitCompareArrows',
  'GitFork',
  'GitGraph',
  'GitMerge',
  'GitPullRequest',
  'GitPullRequestArrow',
  'GitPullRequestClosed',
  'GitPullRequestCreate',
  'GitPullRequestCreateArrow',
  'GitPullRequestDraft',
  'Github',
  'Gitlab',
  'Container',
  'Network',
  'Router',
  'Wifi',
  'WifiOff',
  'Cable',
  'Ethernet',
  'AppWindow',
  'AppWindowMac',
  'PanelLeft',
  'PanelLeftClose',
  'PanelLeftOpen',
  'PanelRight',
  'PanelRightClose',
  'PanelRightOpen',
  'PanelTop',
  'PanelTopClose',
  'PanelTopOpen',
  'PanelBottom',
  'PanelBottomClose',
  'PanelBottomOpen',

  // Communication
  'Users',
  'UsersRound',
  'User',
  'UserCheck',
  'UserCog',
  'UserMinus',
  'UserPlus',
  'UserRound',
  'UserRoundCheck',
  'UserRoundCog',
  'UserRoundMinus',
  'UserRoundPen',
  'UserRoundPlus',
  'UserRoundSearch',
  'UserRoundX',
  'UserSearch',
  'UserX',
  'UserPen',
  'UserCircle',
  'CircleUser',
  'CircleUserRound',
  'Contact',
  'ContactRound',
  'IdCard',
  'PersonStanding',
  'Accessibility',
  'Baby',
  'Handshake',
  'HandMetal',
  'Hand',
  'HandHelping',
  'Grab',
  'MessageSquare',
  'MessageSquareDashed',
  'MessageSquareDiff',
  'MessageSquareDot',
  'MessageSquareHeart',
  'MessageSquareMore',
  'MessageSquareOff',
  'MessageSquarePlus',
  'MessageSquareQuote',
  'MessageSquareReply',
  'MessageSquareShare',
  'MessageSquareText',
  'MessageSquareWarning',
  'MessageSquareX',
  'MessageCircle',
  'MessageCircleCode',
  'MessageCircleDashed',
  'MessageCircleHeart',
  'MessageCircleMore',
  'MessageCircleOff',
  'MessageCirclePlus',
  'MessageCircleQuestion',
  'MessageCircleReply',
  'MessageCircleWarning',
  'MessageCircleX',
  'MessagesSquare',
  'Mail',
  'MailCheck',
  'MailMinus',
  'MailOpen',
  'MailPlus',
  'MailQuestion',
  'MailSearch',
  'MailWarning',
  'MailX',
  'Mails',
  'Mailbox',
  'Send',
  'SendHorizontal',
  'SendToBack',
  'Bell',
  'BellDot',
  'BellMinus',
  'BellOff',
  'BellPlus',
  'BellRing',
  'Megaphone',
  'MegaphoneOff',
  'Phone',
  'PhoneCall',
  'PhoneIncoming',
  'PhoneOutgoing',
  'Video',
  'VideoOff',
  'Mic',
  'MicOff',
  'Mic2',
  'MicVocal',

  // Tools & Actions
  'Settings',
  'Settings2',
  'Cog',
  'SlidersHorizontal',
  'SlidersVertical',
  'Wrench',
  'Hammer',
  'Screwdriver',
  'Axe',
  'Construction',
  'Drill',
  'PenTool',
  'Pen',
  'PenLine',
  'Pencil',
  'PencilLine',
  'PencilRuler',
  'Paintbrush',
  'PaintbrushVertical',
  'Paintbrush2',
  'PaintBucket',
  'Palette',
  'Ruler',
  'Scaling',
  'Scissors',
  'Slice',
  'Eraser',
  'Highlighter',
  'Wand',
  'Wand2',
  'WandSparkles',
  'Search',
  'SearchCheck',
  'SearchCode',
  'SearchSlash',
  'SearchX',
  'Filter',
  'FilterX',
  'SortAsc',
  'SortDesc',
  'ArrowUpAZ',
  'ArrowDownAZ',
  'ArrowUp01',
  'ArrowDown01',
  'ArrowUpZA',
  'ArrowDownZA',
  'ArrowUp10',
  'ArrowDown10',

  // Data & Analytics
  'BarChart',
  'BarChart2',
  'BarChart3',
  'BarChart4',
  'BarChartBig',
  'BarChartHorizontal',
  'BarChartHorizontalBig',
  'LineChart',
  'PieChart',
  'Activity',
  'ActivitySquare',
  'TrendingUp',
  'TrendingDown',
  'Gauge',
  'GaugeCircle',
  'ChartArea',
  'ChartBar',
  'ChartBarBig',
  'ChartBarDecreasing',
  'ChartBarIncreasing',
  'ChartBarStacked',
  'ChartCandlestick',
  'ChartColumn',
  'ChartColumnBig',
  'ChartColumnDecreasing',
  'ChartColumnIncreasing',
  'ChartColumnStacked',
  'ChartLine',
  'ChartNetwork',
  'ChartNoAxesColumn',
  'ChartNoAxesCombined',
  'ChartNoAxesGantt',
  'ChartPie',
  'ChartScatter',
  'ChartSpline',
  'Calculator',
  'Sigma',
  'Pi',
  'Percent',

  // Security & Access
  'Shield',
  'ShieldAlert',
  'ShieldBan',
  'ShieldCheck',
  'ShieldEllipsis',
  'ShieldHalf',
  'ShieldMinus',
  'ShieldOff',
  'ShieldPlus',
  'ShieldQuestion',
  'ShieldX',
  'Lock',
  'LockKeyhole',
  'LockKeyholeOpen',
  'LockOpen',
  'Unlock',
  'UnlockKeyhole',
  'Key',
  'KeyRound',
  'KeySquare',
  'Fingerprint',
  'Eye',
  'EyeOff',
  'ScanEye',
  'ScanFace',
  'Scan',
  'ScanLine',
  'ScanSearch',
  'ScanText',
  'QrCode',

  // Nature & Environment
  'Leaf',
  'LeafyGreen',
  'Clover',
  'Flower',
  'Flower2',
  'TreePine',
  'TreeDeciduous',
  'TreePalm',
  'Trees',
  'Sprout',
  'Vegan',
  'Wheat',
  'WheatOff',
  'Mountain',
  'MountainSnow',
  'Tent',
  'TentTree',
  'Sun',
  'SunDim',
  'SunMedium',
  'SunMoon',
  'SunSnow',
  'Sunrise',
  'Sunset',
  'Moon',
  'MoonStar',
  'CloudMoon',
  'CloudMoonRain',
  'CloudSun',
  'CloudSunRain',
  'CloudRain',
  'CloudRainWind',
  'CloudDrizzle',
  'CloudFog',
  'CloudHail',
  'CloudLightning',
  'CloudSnow',
  'Cloudy',
  'Snowflake',
  'Wind',
  'Waves',
  'Droplet',
  'Droplets',
  'Rainbow',
  'Tornado',
  'Umbrella',
  'UmbrellaOff',
  'Thermometer',
  'ThermometerSnowflake',
  'ThermometerSun',
  'PawPrint',
  'Footprints',
  'Bird',
  'Cat',
  'Dog',
  'Fish',
  'Rabbit',
  'Rat',
  'Shell',
  'Snail',
  'Squirrel',
  'Turtle',
  'Worm',

  // Navigation & Location
  'Compass',
  'Map',
  'MapPin',
  'MapPinned',
  'MapPinOff',
  'MapPinPlus',
  'MapPinCheck',
  'MapPinX',
  'Navigation',
  'Navigation2',
  'NavigationOff',
  'Signpost',
  'SignpostBig',
  'Route',
  'Milestone',
  'Waypoints',
  'Locate',
  'LocateFixed',
  'LocateOff',
  'Move',
  'Move3d',
  'MoveDiagonal',
  'MoveDiagonal2',
  'MoveHorizontal',
  'MoveVertical',

  // Media & Entertainment
  'Music',
  'Music2',
  'Music3',
  'Music4',
  'Headphones',
  'Headset',
  'Speaker',
  'Volume',
  'Volume1',
  'Volume2',
  'VolumeX',
  'AudioLines',
  'AudioWaveform',
  'Radio',
  'RadioReceiver',
  'RadioTower',
  'Podcast',
  'Camera',
  'CameraOff',
  'Image',
  'ImageDown',
  'ImageMinus',
  'ImageOff',
  'ImagePlay',
  'ImagePlus',
  'ImageUp',
  'Images',
  'Film',
  'Clapperboard',
  'Drama',
  'Theater',
  'Tv',
  'Tv2',
  'TvMinimal',
  'TvMinimalPlay',
  'Play',
  'Pause',
  'PlayCircle',
  'PauseCircle',
  'StopCircle',
  'SkipBack',
  'SkipForward',
  'Rewind',
  'FastForward',
  'Gamepad',
  'Gamepad2',
  'Joystick',
  'Dice1',
  'Dice2',
  'Dice3',
  'Dice4',
  'Dice5',
  'Dice6',
  'Dices',
  'Target',
  'Crosshair',
  'Swords',
  'Sword',
  'PartyPopper',
  'Ticket',
  'TicketCheck',
  'TicketMinus',
  'TicketPercent',
  'TicketPlus',
  'TicketSlash',
  'TicketX',
  'Popcorn',

  // Shapes & Geometry
  'Circle',
  'CircleDot',
  'CircleDotDashed',
  'CircleX',
  'Square',
  'SquareDot',
  'SquareDashed',
  'Triangle',
  'TriangleAlert',
  'Diamond',
  'Pentagon',
  'Hexagon',
  'Octagon',
  'Spline',
  'Orbit',
  'Atom',
  'Asterisk',
  'Cube',

  // Arrows & Direction
  'ArrowUp',
  'ArrowDown',
  'ArrowLeft',
  'ArrowRight',
  'ArrowUpDown',
  'ArrowLeftRight',
  'ArrowUpLeft',
  'ArrowUpRight',
  'ArrowDownLeft',
  'ArrowDownRight',
  'ArrowBigUp',
  'ArrowBigDown',
  'ArrowBigLeft',
  'ArrowBigRight',
  'ChevronUp',
  'ChevronDown',
  'ChevronLeft',
  'ChevronRight',
  'ChevronsUp',
  'ChevronsDown',
  'ChevronsLeft',
  'ChevronsRight',
  'ChevronsUpDown',
  'ChevronsLeftRight',
  'MoveUp',
  'MoveDown',
  'MoveLeft',
  'MoveRight',
  'CornerUpLeft',
  'CornerUpRight',
  'CornerDownLeft',
  'CornerDownRight',
  'CornerLeftUp',
  'CornerLeftDown',
  'CornerRightUp',
  'CornerRightDown',
  'Reply',
  'Forward',
  'Repeat',
  'Repeat1',
  'Repeat2',
  'Shuffle',

  // Actions & Controls
  'Plus',
  'PlusCircle',
  'PlusSquare',
  'Minus',
  'MinusCircle',
  'MinusSquare',
  'X',
  'XCircle',
  'XSquare',
  'Download',
  'DownloadCloud',
  'Upload',
  'UploadCloud',
  'Trash',
  'Trash2',
  'Delete',
  'Copy',
  'Clipboard',
  'ClipboardCheck',
  'ClipboardCopy',
  'ClipboardEdit',
  'ClipboardList',
  'ClipboardMinus',
  'ClipboardPaste',
  'ClipboardPen',
  'ClipboardPenLine',
  'ClipboardPlus',
  'ClipboardSignature',
  'ClipboardType',
  'ClipboardX',
  'Save',
  'SaveAll',
  'ExternalLink',
  'Link',
  'Link2',
  'LinkOff',
  'Unlink',
  'Unlink2',
  'Share',
  'Share2',
  'Maximize',
  'Maximize2',
  'Minimize',
  'Minimize2',
  'Expand',
  'Shrink',
  'ZoomIn',
  'ZoomOut',
  'Import',
  'FolderDown',
  'FolderUp',

  // Power & Energy
  'Power',
  'PowerOff',
  'PowerCircle',
  'Plug',
  'Plug2',
  'PlugZap',
  'PlugZap2',
  'Unplug',
  'Cable',
  'CableCar',
  'Battery',
  'BatteryCharging',
  'BatteryFull',
  'BatteryLow',
  'BatteryMedium',
  'BatteryWarning',
  'Fuel',
  'Bolt',
  'Flashlight',
  'FlashlightOff',
  'Lamp',
  'LampCeiling',
  'LampDesk',
  'LampFloor',
  'LampWallDown',
  'LampWallUp',
  'Lightbulb',
  'LightbulbOff',

  // Medical & Science
  'Stethoscope',
  'Pill',
  'PillBottle',
  'Syringe',
  'TestTube',
  'TestTube2',
  'TestTubes',
  'FlaskConical',
  'FlaskConicalOff',
  'FlaskRound',
  'Microscope',
  'Dna',
  'DnaOff',
  'Hospital',
  'Ambulance',
  'Cross',
  'Bone',
  'Skull',
  'Ear',
  'EarOff',

  // Transportation
  'Car',
  'CarFront',
  'CarTaxiFront',
  'Bus',
  'BusFront',
  'Truck',
  'Train',
  'TrainFront',
  'TrainFrontTunnel',
  'TrainTrack',
  'TramFront',
  'Bike',
  'Plane',
  'PlaneLanding',
  'PlaneTakeoff',
  'Ship',
  'Sailboat',
  'Anchor',
  'Satellite',
  'SatelliteDish',

  // Food & Drink
  'Coffee',
  'CupSoda',
  'GlassWater',
  'Wine',
  'Beer',
  'Martini',
  'Milk',
  'MilkOff',
  'IceCream',
  'IceCreamCone',
  'IceCreamBowl',
  'Cake',
  'CakeSlice',
  'Cookie',
  'Croissant',
  'Pizza',
  'Sandwich',
  'Salad',
  'Soup',
  'UtensilsCrossed',
  'Utensils',
  'ChefHat',
  'CookingPot',
  'Refrigerator',
  'Microwave',
  'Oven',
  'Apple',
  'Banana',
  'Cherry',
  'Citrus',
  'Grape',
  'Lemon',
  'Nut',
  'NutOff',
  'Carrot',
  'Egg',
  'EggFried',
  'EggOff',
  'Ham',
  'Beef',
  'Drumstick',
  'FishOff',
  'FishSymbol',
  'Candy',
  'CandyCane',
  'CandyOff',
  'Lollipop',

  // Shopping & Commerce
  'ShoppingCart',
  'ShoppingBag',
  'ShoppingBasket',
  'CreditCard',
  'Wallet',
  'WalletCards',
  'WalletMinimal',
  'DollarSign',
  'Euro',
  'PoundSterling',
  'Coins',
  'Banknote',
  'BadgeDollarSign',
  'BadgeEuro',
  'BadgePoundSterling',
  'CircleDollarSign',
  'Receipt',
  'ReceiptText',

  // Misc Symbols
  'Hash',
  'AtSign',
  'Infinity',
  'Omega',
  'Divide',
  'Equal',
  'NotEqual',
  'Ampersand',
  'Slash',
  'SlashSquare',
  'StickyNote',
  'Type',
  'ALargeSmall',
  'CaseLower',
  'CaseSensitive',
  'CaseUpper',
  'Bluetooth',
  'Siren',
  'HelpCircle',
  'CircleHelp',
  'ParenthesesIcon',
  'BracesIcon',
  'BracketsIcon'
] as const
